name: Track Recently Modified Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  track-modifications:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Get the list of recently modified files
      - name: Get Recently Modified Files
        id: modified-files
        run: |
          git fetch --all
          if git rev-parse HEAD^ > /dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD > modified-files.txt
          else
            echo "Initial commit detected. Listing all files:" > modified-files.txt
            git ls-files >> modified-files.txt
          fi
          echo "Modified files:"
          cat modified-files.txt

      # Step 3: Upload the modified files list as an artifact
      - name: Upload Modified Files Artifact
        uses: actions/upload-artifact@v3
        with:
          name: modified-files
          path: modified-files.txt

      # Step 4: Download and verify the modified files artifact
      - name: Download Modified Files Artifact
        uses: actions/download-artifact@v3
        with:
          name: modified-files
          path: ./modified-files.txt

      - name: Show Downloaded Artifact
        run: cat ./modified-files.txt
